#!/usr/bin/perl
use strict;
use warnings;

use CGI;

# YES I JUST DID THIS AND I'M NOT SORRY lol data is fun:

my @lines = (
    q[A can of %s, 73 pigeons, some LIVE ammo, and a %s!!],
    q[A dwarf is passing out somewhere in Detroit!],
    q[%s?? %s... %s... %s... Oh, Yeh!! Wash the ROOM!!],
    q[...A housewife is wearing a polypyrene jumpsuit!!],
    q[A shapely %s is %s inside my costume..],
    q[A wide-eyed, innocent %s, poised delicately in a %s filled with %s, %s & small %s at the HUSH of twilight??],
    q[Actually, what I'd like is a little toy spaceship!!],
    q[After this, I'm going to BURN some %s!!],
    q[After THIS, let's go to %s and have %s!!],
    q[%s! I am having an %s!],
    q[%s! Say something about th' DEATH of DISCO!!],
    q[All I can think of is a platter of organic %s being trampled by an army of swarthy, Italian %s...],
    q[All of a sudden, I want to %s my promising %s, grow a %s and wear a %s!! ... Although I don't know WHY!!],
    q[All of life is a blur of Republicans and meat!],
    q[All right, you degenerates! I want this place evacuated in 20 seconds!],
    q[All this time I've been %s a %s a %s!],
    q[Alright, you!! Imitate a %s pleading for a %s!!],
    q[Am I accompanied by a %s or %s?],
    q[Am I elected yet?],
    q[..Am I in a %s??],
    q[Am I in %s yet?],
    q[Am %s?],
    q[America!! I saw it all!! Vomiting! Waving! %s into your void tube of UHF oblivion!! %s of the mind --],
    q[An air of %s permeates my nostrils!!],
    q[An INK-LING? Sure -- TAKE one!! Did you BUY any %s??],
    q[An Italian is %s his hair in suburban %s!],
    q[And furthermore, my bowling average is unimpeachable!!!],
    q[%s'%s makes %s'%s look like %s'%s!],
    q[Are %s.V.S on??],
    q[.. are the %s still in the %s?],
    q[..Are we having FUN yet...?],
    q[Are we live or on tape?],
    q[Are we on %s yet?],
    q[Are we THERE yet?],
    q[Are we THERE yet? My MIND is a %s!!],
    q[Are we THERE yet?!],
    q[Are we THERE yet??],
    q[Are you guys lined up for the %s or %s??],
    q[Are you mentally here at Pizza Hut??],
    q[Are you selling %s?? If so, we can use %s!!],
    q[Are you still an %s?],
    q[Are you still %s? Did you BRING th' %s?],
    q[As a FAD follower, my %s choices are rich and fulfilling!],
    q[As President I have to go vacuum my coin collection!],
    q[Ask me the %s between %so%s and %s!!],
    q[Awright, which one of you hid my %s?],
    q[Bagels...],
    q[%s makes me nervous!!],
    q[Barbie says, Take quaaludes in gin and go to a disco right away! But Ken says, WOO-WOO!! No credit at ``Mr. Liquor''!!],
    q[BARRY.. That was the most HEART-%s rendition of ``%s'' I've ever heard!!],
    q[BEEP-BEEP!! I'm a '49 %s!!],
    q[Being a %s is almost as %s as a %s.],
    q[%s is my co-pilot..],
    q[BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-],
    q[... Blame it on the %s!!!],
    q[.. bleakness.... desolation.... plastic forks...],
    q[Bo Derek ruined my life!],
    q[Boy, am I glad it's only 1971...],
    q[Boys, you have ALL been selected to LEAVE th' %s in 15 minutes!!],
    q[%s is %s' WHEAT in another %s..],
    q[But was he mature enough last night at the lesbian masquerade?],
    q[By MEER biz doo %s..],
    q[C'MON, everybody!! I've flown in %s and two dozen %s! They'll be doing intricate %s to the soundtrack from "%s"!!],
    q[%s is where people from IOWA or %s go to subscribe to %s!!],
    q[Can I have an %s instead?],
    q[Can you MAIL a %s?],
    q[Catsup and Mustard all over the place! It's the Human Hamburger!],
    q[%s just had a %s in downtown %s!],
    q[%s owns my %s!],
    q[Civilization is fun! Anyway, it keeps me busy!!],
    q[Clear the laundromat!! This whirl-o-matic just had a nuclear meltdown!!],
    q[Concentrate on th'cute, li'l %s! Remember the %s!! Follow the %s!! Have a %s!! Turn LEFT at th'%s!! JOIN the %s!! MAKE me an OFFER!!!],
    q[%s! Now should I make thinly veiled comments about %s, self-esteem and finding %s in your %s??],
    q[Content: 80% %s, 20% %s.. The waitress's %s sheds %s like an 8'' by 10'' %s..],
    q[Could I have a drug overdose?],
    q["%s" is on!! Hey, I think the %s forgot his %s!!],
    q[Darling, my ELBOW is %s over %s, Germany..],
    q[Dehydrated EGGS are %s across %s..],
    q[Did an Italian %s just experience uninhibited sensations in a %s?],
    q[Did I do an %s??],
    q[Did I say I was a sardine? Or a bus???],
    q[Did %s yet??],
    q[Did we bring enough %s?],
    q[Did YOU find a %s in YOUR box of %s?],
    q[Did you find a %s in YOUR box of %s??],
    q[Did you %s in th' past 5 %s or am I just %s of two %s lying in an empty %s?],
    q[Did you move a lot of %s this trip, Dingy?],
    q[DIDI... is that a %s name, or, are we in %s?],
    q[Didn't I buy a 1951 Packard from you last March in Cairo?],
    q[Didn't %s wear out his TIRES in %s during a %s of FREUD's unpaid %s?],
    q[Disco oil bussing will create a throbbing naugahide pipeline running straight to the tropics from the rug producing regions and devalue the dollar!],
    q[Dizzy, are we "%s" or "%s"?],
    q[Do I have a lifestyle yet?],
    q[Do I hear th' %s of various %s, ROUND, and %s?!],
    q[Do you guys know we just passed thru a %s in space?],
    q[Do you have exactly what I want in a plaid poindexter bar bat??],
    q[.. Do you like ``%s?''?],
    q[Do you need any MOUTH-TO-MOUTH resuscitation?],
    q[Do you think the ``Monkees'' should get gas on odd or even days?],
    q[Does someone from %s have a %s span than me?],
    q[Does that mean I'm not a well-adjusted person??],
    q[.. does your %s have enough %s?],
    q[DON'T go!! I'm not %s!! I know %s... WAIT!! Don't go!! %soward Cosell!... And I DON'T know Polish jokes!!],
    q[Don't hit me!! I'm in the Twilight Zone!!!],
    q[Don't %s me!!],
    q[Don't worry, nobody really %s to lectures in %s, either! .. %s, %s, %s, %s, %s, %s!.. Are there any %s??],
    q[Edwin Meese made me wear %s!!],
    q[Eisenhower!! Your mimeograph machine upsets my stomach!!],
    q[Either %s now or we go to ``%s'%s''!!],
    q[Everybody gets free %s!],
    q[Everybody is going somewhere!! It's probably a garage sale or a disaster Movie!!],
    q[..Everything is....%s!!],
    q[Everything will be %s if we can just remember things about %s.. or %s.. or %s..],
    q[Everywhere I look I see %s and %s...],
    q[Excuse me, but didn't I tell you there's %s for the survival of %s?],
    q[%s are cascading over me!!!],
    q[Fell th' %s buffing away all that stress... Years of %s gently washing away...],
    q[Finally, Zippy drives his 1958 %s into the faculty dining room.],
    q[FIRST, I was in a TRUCK...THEN, I was in a DINER...],
    q[FIRST, I'm covering you with %s and %s!!],
    q[First, I'm going to give you all the %s to today's test.. So just plug in your %s and relax!!],
    q[FISH-NET-FISH-NET-FISH-NET-FISH-NET-FISH!!],
    q[Fold, fold, FOLD!! %s many items!!],
    q[%s you! Absorb %s impulse rays, polyester poltroon!!],
    q[Four thousand different %s, %s & %s are romping in my gothic solarium!!],
    q[%s may be flung by members of opposing %s..],
    q[FUN is never having to say you're SUSHI!!],
    q[Gee, I feel kind of LIGHT in the head now, knowing I can't make my satellite dish %s!],
    q[...Get me a GIN and TONIC!!...make it %s!!],
    q[Gibble, Gobble, we %s ---],
    q[Give them RADAR-%s-%s and %s!!],
    q[Go on, EMOTE! I was %s on thought balloons!!],
    q[GOOD-NIGHT, everybody.. Now I have to go administer FIRST-AID to my pet %s!!],
    q[Ha ha Ha ha Ha ha Ha Ha Ha Ha -- When will %s stop %s?!!],
    q[%s, please!!],
    q[Half a mind is a terrible thing to waste!],
    q[Hand me a pair of leather pants and a CASIO keyboard -- I'm living for today!],
    q[Has everybody got %s spread all over their %s??... Now, it's time to ``%s''!!],
    q[Have my two-tone, 1958 Nash METRO brought around..],
    q[.. he dominates the %s.],
    q[He is the MELBA-BEING... the %s... XEROX him... XEROX him --],
    q[He probably just wants to take over my CELLS and then %s inside me like a %s of runny %s! Or maybe he'd like to %s until I have no objection to a RIGHT-%s of my apartment!! I guess I should call %s!],
    q[%s gang terrorizes town, family %s to death!],
    q[HELLO, everybody, I'm a HUMAN!!],
    q[Hello, GORRY-O!! I'm a %s from %s!!],
    q[HELLO, little boys! Gimme a %s!! Let's do the %s!!],
    q[--Hello, %s? I"ve got %s & %s here on suspicion of %s!!],
    q[Hello. I know the divorce rate among unmarried Catholic Alaskan females!!],
    q[Hello. Just walk along and try NOT to think about your %s being almost %s!!],
    q[Hello... %s? Send over a %s! World War III? No thanks!],
    q[Hello? Enema Bondage? I'm calling because I want to be happy, I guess..],
    q[Here I am at the flea market but nobody is buying my urine sample bottles..],
    q[.. here I am in 53 B.C. and all I want is a dill pickle!!],
    q[Here I am in the %s but I don't see %s anywhere!!],
    q[Here is my refrigerator full of %s...and over there is my %s...I don't know %s them!!],
    q[Here we are in America... when do we collect unemployment?],
    q[HERE!! Put THIS on!! I'm in %s!!],
    q[Hey!! Let's watch the' %s go UP and DOWN at th' %s!!],
    q[Hey, %s that POINT!!],
    q[Hey, LOOK!! A pair of SIZE 9 %s!! They probably belong to %s, JR.!!],
    q[Hey, wait a minute!! I want a divorce!!.. you're not Clint Eastwood!!],
    q[Hey, waiter! I want a %s and a %s with lemon sauce!],
    q[Hiccuping & trembling into the %s of New Jersey like some drunken %s, coughing in line at %s'S!!],
    q[Hmmm.. a %s with a %s sandwich is HIT by a %s-CAR..],
    q[Hmmm.. A hash-singer and a cross-eyed guy were %s on a desertedisland, when...],
    q[Hmmm... a %s, during an %s, encounters an ALL-%s... ha.. ha..],
    q[Hmmm... an arrogant bouquet with a subtle suggestion of %s...],
    q[Hold the MAYO & pass the %s...],
    q[%s, Ronald!! Now YOU can marry %s too!!],
    q[HOW could a GLASS be %s??],
    q[How do I get HOME?],
    q[How do you explain Wayne Newton's POWER over millions? It's th' %s... Have you ever noticed th' way it radiates %s, %s & %s? It's a %s you want to take HOME and introduce to %s!],
    q[How many retired bricklayers from %s are out purchasing %s right NOW??],
    q[How's it going in those %s??],
    q[How's the wife? Is she at home enjoying capitalism?],
    q[.. hubub, hubub, HUBUB, hubub, hubub, hubub, HUBUB, hubub, hubub, hubub.],
    q[%s died in 1982!!],
    q[%s are inserted into VATS of %s...],
    q[Hydraulic pizza oven!! Guided missile! Herring sandwich! Styrofoam! Jayne Mansfield! Aluminum siding! Borax! Pedal pushers! Jukebox!],
    q[I always have fun because I'm out of my mind!!!],
    q[I always liked %s!!],
    q[I always wanted a %s!!],
    q[I am a jelly donut. I am a jelly donut.],
    q[I am a traffic light, and Alan Ginzberg kidnapped my laundry in 1927!],
    q[I am covered with pure vegetable oil and I am writing a best seller!],
    q[I am deeply %s and I want something GOOD for %s!],
    q[I am having a %s--],
    q[I am having a pleasant time!!],
    q[I am having FUN... I wonder if it's %s or %s?],
    q[I am %s of Sicily!..I will marry %s next Friday!],
    q[I am NOT a nut....],
    q[I appoint you ambassador to Fantasy Island!!!],
    q[I brought my %s - and some DRUGS!!],
    q[I call it a "%s"!],
    q[-- I can do %s ... I can even ... %s!!],
    q[I can see you GUYS an' GALS need a LOT of HELP...You're all very %s!! I used to be %s, too..before I started watching UHF-TV!!],
    q[I can't decide which %s to make first!! I wonder if %s has these problems!],
    q[I can't think about that. It doesn't go with %s in the shape of %s -- or %s making %s...],
    q[I decided to be %s instead!!],
    q[I demand %s!],
    q[I didn't order any WOO-WOO... Maybe a YUBBA.. But no WOO-WOO!],
    q[I don't believe there really IS a %s.. I think it's all just a %s on the part of the plastic sign salesmen-.. to sell more numbers!!],
    q[.. I don't know why but, suddenly, I want to discuss declining I.Q. %s with a blue ribbon %s-%s!],
    q[I don't know WHY I said that.. I think it came from the %s in my rear molars..],
    q[I don't think you fellows would do so much %s and %s if you played more %s and watched %s!!],
    q[.. I don't understand the HUMOR of the %s!!],
    q[I feel better about world problems now!],
    q[I feel like a wet parking meter on Darvon!],
    q[I feel like I am sharing a ``CORN-DOG'' with %s..],
    q[I feel like I'm in a Toilet Bowl with a thumbtack in my forehead!!],
    q[I feel partially hydrogenated!],
    q[I feel real %s being in %s!],
    q[.. I feel.. %s..],
    q[I fill MY industrial waste containers with old copies of the ``%s'' and then add %s to the top.. They look NICE in the yard--],
    q[%s to do the %s!!],
    q[I guess it was all a DREAM.. or an episode of %s-O...],
    q[I guess we can live on his %s in HADES!!],
    q[I guess you guys got %s from doing too much %s!],
    q[I had a lease on an %s back in '81...],
    q[I had pancake makeup for brunch!],
    q[I have a %s in my HEAD],
    q[%s a towel.],
    q[I have a very good %s. Thank you.],
    q[.. I have a %s! It's a %s double-%s on an %s!!],
    q[I have accepted Provolone into my life!],
    q[I have many %s and %s..],
    q[I have no actual hairline...],
    q[I have nostalgia for the late Sixties! In 1969 I left my laundry with a hippie!! During an unauthorized tupperware party it was chopped & diced!],
    q[--- I have seen the FUN ---],
    q[I have seen these %s in my Supermarket.. .. I have read the %s...],
    q[I have the power to %s on all %s!!],
    q[%s to buy a new ``%s'' and two dozen %s because my viewscreen is ``USER-%s''!!],
    q[I haven't been married in over six years, but we had sexual counseling every day from Oral Roberts!!],
    q[%s a 747 to get here!! I hope those fabulous %s are at HOME!!],
    q[I hope I bought the right relish... zzzzzzzzz...],
    q[I hope something GOOD came in the mail today so I have a %s to live!!],
    q[I hope the ``Eurythmics'' practice birth control...],
    q[I hope you millionaires are having fun! I just invested half your life savings in yeast!!],
    q[I invented skydiving in 1989!],
    q[I joined scientology at a garage sale!!],
    q[I just bought %s from %s!],
    q[I just forgot my whole philosophy of life!!!],
    q[I just got my %s bumper sticker.. But now I can't remember WHO he is...],
    q[I just had a %s with %s!!],
    q[I just had a %s!!],
    q[I just had my entire %s coated with %s!],
    q[I just heard the %s were over!! And I was just getting in touch with my %s!!],
    q[I just put lots of the %s in the %s --],
    q[I just remembered something about a TOAD!],
    q[..I just walked into th' %s with fourteen %s and an out-of-date %s...],
    q[%s?! What good is a Kaiser Roll without a little %s on the SIDE?],
    q[I Know A Joke],
    q[I know how to do %s!!],
    q[I know how to get the hostesses released! Give them their own television series!],
    q[I know th'MAMBO!! I have a TWO-%s!!],
    q[I know things about %s that can't even be %s!!],
    q[I left my %s in the %s!!],
    q[%sisle 7a.],
    q[I like the %s on that car.. Are you a TEEN-AGER? ],
    q[I like the way ONLY their mouths move.. They look like %s],
    q[I like your %s!!],
    q[... I live in a FUR-%s],
    q[I love %s!!],
    q[--``I love %s because she drives a %s. We're going away now. I fed the cat. - Zippy''],
    q[I love ROCK '%s! I memorized the all WORDS to ``WIPE-OUT'' in 1965!!],
    q[..I must be a %s..],
    q[I need "RONDO".],
    q[I need to discuss BUY-%s with at least six studio %s!!],
    q[I once decorated my apartment entirely in ten foot salad forks!!],
    q[I own seven-eighths of all the artists in downtown Burbank!],
    q[I OWN six pink %s!!],
    q[I predict that by 1993 everyone will live in and around %s and wear %s!],
    q[I pretend I'm living in a styrofoam packing crate, high in th' %s, still unable to accept th' idea of TOUCH-%s!!],
    q[I put aside my copy of ``%s'' and think about %s legislation..],
    q[I represent a sardine!!],
    q[I request a weekend in Havana with Phil Silvers!],
    q[.. I see %s...],
    q[I selected E5... but I didn't hear ``Sam the Sham and the Pharaohs''!],
    q[I smell a %s!],
    q[I smell like a wet reducing clinic on Columbus Day!],
    q[I think I am an overnight sensation right now!!],
    q[.. I think I'd better go back to my DESK and toy with a few common %s...],
    q[I think I'll do BOTH if I can get %s!!],
    q[.. I think I'll KILL myself by leaping out of this 14th %s while reading %s'S poetry!!],
    q[I think I'll make %s!! They're each in %s..],
    q[...I think I'm having an overnight sensation right now!!],
    q[I think my career is ruined!],
    q[I think my %s is %s!!],
    q[I used to be a %s, but then I heard about the %s and bought an %s!!],
    q[.. I want a %s.V. and a %s!!!],
    q[I want a %s to go.. with %s!!],
    q[I want a %s lease!!],
    q[I want another RE-WRITE on my %s!!],
    q[I want %s!! .. I want %s!! YOW!!],
    q[I want EARS! I want two %s to make me feel warm 'n secure!!],
    q[.. I want FORTY-%s installed within %s!!!],
    q[I want the presidency so bad I can already taste the hors d'oeuvres.],
    q[I want to dress you up as %s and cover you with %s and %s..],
    q[I want to kill everyone here with a cute colorful Hydrogen Bomb!!],
    q[.. I want to perform cranial activities with Tuesday Weld!!],
    q[I want to read my new poem about pork brains and outer space...],
    q[I want to so HAPPY, the VEINS in my neck %s!!],
    q[I want to %s and %s in %s!!],
    q[I want you to %s the collected poems of %s.. %s!!],
    q[I want you to organize my %s trays... my TEA-TINS are gleaming in formation like a ROW of %s -please don't be %s with me --],
    q[I was born in a Hostess Cupcake factory before the sexual revolution!],
    q[I was giving %s to th' %s .. I'm CLEAN!!],
    q[I was in a %s! I was %s! I was %s!! I enjoyed th' %s!],
    q[I was in %s until I started reading %sagazine!!],
    q[I was making donuts and now I'm on a bus!],
    q[I will establish the first %s in %s, New Jersey...],
    q[I will invent "%s"...],
    q[I will SHAVE and buy JELL-O and bring my %s!!],
    q[I wish I was a sex-starved manicurist found dead in the Bronx!!],
    q[I wish I was on a Cincinnati street corner holding a clean dog!],
    q[I wonder if I could ever get started in the credit world?],
    q[.. I wonder if I ought to tell them about my %s as a %s?],
    q[I wonder if I should put myself in %s!!],
    q[I wonder if there's anything GOOD on tonight?],
    q[I would like to urinate in an %s, porcelain pool --],
    q[I'd like MY data-base %s and stir-fried!],
    q[I'd like some %s... and then I want to be ALONE --],
    q[I'd like %s and a %s on my doorstep by NOON!!],
    q[I'll clean your ROOM!! I know some GOOD stories, too!! All about %ssland's, %suppies, and how LUKE finds GOLD on his LAND!!],
    q[I'll eat %s that's %s!!],
    q[I'LL get it!! It's probably a FEW of my %s-%s!!],
    q[..I'll make you an %s!!],
    q[I'll show you MY telex number if you show me YOURS...],
    q[I'll take %s if you're out of LAMB!!],
    q[I'm a fuschia bowling ball somewhere in Brittany],
    q[I'm a %s! I want to dispute sentence structure with %s!!],
    q[I'm a nuclear submarine under the polar ice cap and I need a Kleenex!],
    q[I'm also against BODY-%s!!],
    q[I'm also pre-%s pre-%s and pre-%s!!],
    q[I'm an East Side TYPE..],
    q[I'm %s!! I can %s!!],
    q[I'm %s!! I can %s!!],
    q[I'm changing the %s.. But all I get is commercials for ``%s''!],
    q[I'm continually %s at th'breathtaking effects of %s!!],
    q[I'm %s by the CIA!! %s is controlled by the CIA!!],
    q[I'm definitely not in Omaha!],
    q[I'm %s... I hope there's something DEEP-FRIED under this miniature %s...],
    q[I'm dressing up in an ill-fitting IVY-%s!! Too late...],
    q[I'm %s now because I have %s!!],
    q[I'm encased in the lining of a pure pork sausage!!],
    q[I'm %s!! I want a %s-END!! I think I'm %s!!],
    q[I'm %s remembered to XEROX all my %s!!],
    q[I'm gliding over a %s near %s, Georgia!!],
    q[I'm having a %s!!],
    q[I'm having a MID-%s!],
    q[I'm having a %s.. and I don't take any DRUGS],
    q[I'm having a tax-deductible experience! I need an energy crunch!!],
    q[I'm having an emotional outburst!!],
    q[I'm having an %s!! But, uh, WHY is there a %s in my %s??],
    q[I'm having %s about the %s of smug and wealthy %s..],
    q[I'm having fun %s to %s or %s!!],
    q[.. I'm %s a sensuous %s, %s in the %s of a %s --],
    q[I'm in a twist contest!! I'm in a bathtub! It's on Mars!! I'm in tip-top condition!],
    q[I'm in %s riding in a comfortable %s...],
    q[I'm in direct contact with many advanced fun %s.],
    q[I'm in %s as a %s....I can watch the house, if it's %s...],
    q[I'm in LOVE with %s!!],
    q[I'm into %s!],
    q[I'm losing my hair..did it go to %s??],
    q[I'm meditating on the %s and the %s leaking into my %s!!],
    q[I'm %s here.. but %s'm purchasing %s furniture in the' %s of %s!!],
    q[I'm mentally %s! What's that %s up ahead? Where's %s when you really need him?],
    q[I'm not an Iranian!! I voted for Dianne Feinstein!!],
    q[I'm not available for comment..],
    q[I'm pretending I'm pulling in a TROUT! Am I doing it correctly??],
    q[I'm pretending that we're all watching %s instead of %s!],
    q[I'm protected by a ROLL-ON I rented from AVIS..],
    q[I'm %s reading the latest issue of ``%s'' while my wife and two children stand %s..],
    q[I'm rated PG-34!!],
    q[I'm receiving a coded message from %s!!],
    q[I'm %s!! I love a man with a %s!! Equip me with %s!!],
    q[I'm reporting for duty as a modern person. I want to do the Latin Hustle now!],
    q[I'm shaving!! I'%s!!],
    q[I'm sitting on my %s.. To me, it's %s.. I'm WARM.. I'm %s..],
    q[I'm thinking about %s-OUT systems and computer-generated %s..],
    q[I'm totally %s over the %s situation and the price of %s..],
    q[I'm using my X-%s to obtain a rare glimpse of the %s of this %s!!],
    q[I'm wearing %s!!],
    q[I'm wet! I'm wild!],
    q[I'm working under the direct orders of %s to deport consenting adults!],
    q[I'm young.. I'm %s.. I can %s'%s!],
    q[I'm ZIPPY the %s and I'm totally committed to the festive mode.],
    q[I'm ZIPPY!! Are we having FUN yet??],
    q[I've been %s to %s every 45 %s since %s 1ST!!],
    q[I've got a %s who works in the %s...],
    q[I've got an IDEA!! Why don't %s at you so HARD, you forget your %s!!],
    q[I've got to get these %s to %s by DAWN!!],
    q[I've gotta GO, now!! I wanta tell you you're a GREAT bunch of guys but you ought to %s your %s more often!!],
    q[I've read %s books!!],
    q[.. ich bin in einem dusenjet ins jahr 53 vor chr... ich lande im antiken Rom... einige gladiatoren spielen scrabble... ich rieche PIZZA...],
    q[If a person is %s in this country, they have to go on the ROAD for %s at a time and have their name misspelled on the SIDE of a %s!!],
    q[If elected, Zippy pledges to each and every American a 55-year-old houseboy...],
    q[If I am elected no one will ever have to do their laundry again!],
    q[If I am elected, the concrete barriers around the %s will be replaced by tasteful foam replicas of %s!],
    q[.. If I cover this entire WALL with %s, wdo I have to give my AGENT ten per cent??],
    q[If I felt any more %s would DIE of %s!],
    q[If I had a Q-TIP, I could prevent th'collapse of %s!!],
    q[.. If I had heart failure right now, I couldn't be a more fortunate man!!],
    q[If I have enough money to buy 5,000 CANS of %s-RONI, can I get a VAT of %s free??],
    q[If I pull this %s'll be %s!! Or a %s!],
    q[- if it %s, gobble it!!],
    q[If our behavior is strict, we do not need fun!],
    q[If Robert Di Niro assassinates Walter Slezak, will Jodie Foster marry Bonzo??],
    q[If this is the %s want to know your %s! Do I get th' %s?],
    q[If this was a %s, I'd take off your GO-%s!!],
    q[If you STAY in China, I'll give you 4,000 %s of "%s" pencil sharpeners!!],
    q[Imagine--a WORLD without %s...],
    q[Impudent.. Yet possessing a certain %s overbite....Needs REDDY-WHIP!!],
    q[-- In 1962, you could buy a pair of %s, with a ``Continental Belt,'' for $10.99!!],
    q[In Newark the laundromats are open 24 hours a day!],
    q[In order to make PLANS for the %s...so that we can read %s and decide to GO to that restaurant & then %s...so we can meet a %s after work in a BAR and %s about Interior Sect'y %s until the %s is changed to %s...and so our %s can FORCE us to listen to %s while we wait for them to LEAVE on the 7:48....],
    q[%s, I have the same personality disorder as %s!!],
    q[Inside, I'm already %s!],
    q[Intra-mural sports results are filtering through th' plumbing...],
    q[Is a tattoo real, like a curb or a battleship? Or are we suffering in Safeway?],
    q[Is it 1974? What's for %s? Can I spend my %s in one wild afternoon??],
    q[Is it clean in other dimensions?],
    q[Is it FUN to be a %s?],
    q[Is it %s when 3 olives are struggling with a scallop in a plate of %s?],
    q[Is something %s going to happen to a %s?],
    q[Is the %s when they had %s and %scBOING-BOING lunch boxes??],
    q[Is there something I should be DOING with a %s??],
    q[Is this "%s"?],
    q[Is this "BOOZE"?],
    q[Is this an out-take from the ``%s''?],
    q[Is this %s, USA?],
    q[Is this BOISE??],
    q[Is this going to involve RAW human ecstasy?],
    q[Is this my STOP??],
    q[Is this %s fun?],
    q[Is this the line for the latest whimsical %s drama which also makes you want to CRY and reconsider the %s?],
    q[Is this where people are HOT and NICE and they give you TOAST for FREE??],
    q[Isn't this my STOP?!],
    q[It don't mean a THING if you ain't got that SWING!!],
    q[It was a JOKE!! Get it?? I was receiving messages from %s!! YOW!!],
    q[It's 74 degrees, 12 minutes NORTH, and 41 degrees, 3 minutes EAST!! Soon, it will be %s!!],
    q[It's a lot of fun being alive... I wonder if my bed is made?!?],
    q[It's hard being an %s!!],
    q[It's %s.. I've gone to ``%s''!!],
    q[It's %s.. The FURS never reached %s.. You were an EXTRA in the %s of ``%s''.. Go home to your WIFE.. She's making %s!],
    q[It's OKAY --- I'm an %s, too.],
    q[...It's %s.. And it's got a %s right in the %s!! The shape is %s.. ..And COLD.. It feels very %s on my CHEEK.. I'm getting %s..],
    q[It's so %s!!],
    q[It's strange, but I'm only %s when I'm covered in %s and %s...],
    q[It's the land of %s as promised in %s!],
    q[It's the %s!! They've %s the %s!!],
    q[It's today's %s!],
    q[JAPAN is a %s planet -- I wonder if we'll ever reach their level of %s...],
    q[Jesus is my %s..],
    q[Join the %s'%s!!],
    q[...Just enough time to do my %s impression...],
    q[Just imagine you're entering a state-of-the-art %s!!],
    q[Just to have %s, I'll pretend I am %s and I am having a tense, UP-%s!!],
    q[%s'%s just won an %s!!],
    q[Kids, don't gross me off.. ``Adventures with %s'' can be carried too FAR!],
    q[Kids, the seven basic food groups are GUM, %s, PIZZA, %s, %s, NUTRA-SWEET and %s!!],
    q[Laundry is the fifth dimension!! ...um...um... th' washing machine is a black hole and the pink socks are bus drivers who just fell in!!],
    q[LBJ, LBJ, how many JOKES did you tell today??!],
    q[Leona, I want to %s things to you.. I want to WRAP you in a %s trimmed with %s.. I want to EMPTY your %s...],
    q[Let me do my %s to %s...],
    q[Let's all show human %s for %s's legal difficulties!!],
    q[Let's climb to the TOP of that %s and think about %s!!],
    q[Let's go to %s!],
    q[Let's send the Russians defective lifestyle accessories!],
    q[LIFE is a never-ending %s!],
    q[Life is a %s! I'm %s!!],
    q[Life is selling %s!],
    q[.. Like I always say -- nothing can beat the %s here in %s!!],
    q[Loni Anderson's hair should be %s!!],
    q[Look DEEP into the %s!! Do you see any ELVES or %s... or a %s??...],
    q[Look into my eyes and try to forget that you have a Macy's charge card!],
    q[Look! A ladder! Maybe it leads to heaven, or a sandwich!],
    q[Look!! Karl Malden!],
    q[LOOK!! Sullen American teens wearing %s shorts and ``Flock of Seagulls'' %s!],
    q[LOOK!!! I'm %s in my SLEEP again!!],
    q[%s froze my %s!!],
    q[Make me look like %s again!!],
    q[Mary Tyler Moore's %s is wearing my %s in a cheap hotel in %s!],
    q[Maybe we could paint %s a rich %s--],
    q[%s is my obstetrician!],
    q[MMM-MM!! So THIS is BIO-%s!],
    q[Mmmmmm-%s!! A plate of %s of a PIG mixed with the shreds of %s!!... Oh BOY!! I'm about to swallow a TORN-OFF section of a COW'%s soaked in %s and SUGAR!! .. Let's see.. Next, I'll have the %s-UP flesh of CUTE, %s fried in the %s, %s from a warm-blooded animal someone once %s!! ... YUM!! That was GOOD!! For %s, I'll have a %s with %s on a stone-ground, %s!!],
    q[Mr and Mrs PED, can I borrow 26.7% of the %s production of the %s archipelago?],
    q[My Aunt %s was a military advisor to IKE & %s!!],
    q[My %s just went off.. It has noiseless %s and full kitchen!!],
    q[My CODE of %s is vacationing at famed %s in upstate New York!!],
    q[My %s has an automatic %s!!],
    q[My EARS are GONE!!],
    q[My ELBOW is a remote %s!!],
    q[My face is new, my license is expired, and I'm under a doctor's care!!!!],
    q[My %s group is "%s & %s"...],
    q[My forehead feels like a %s of moist %s in a remote %s!!],
    q[My haircut is totally traditional!],
    q[MY income is ALL disposable!],
    q[My %s record is %s..],
    q[My %s expired...],
    q[My life is a patio of fun!],
    q[My mind is a potato field...],
    q[My mind is making ashtrays in Dayton....],
    q[My nose feels like a bad Ronald Reagan movie...],
    q[.. my NOSE is NUMB!],
    q[.. My pants just went on a wild rampage througha Long Island Bowling Alley!!],
    q[My pants just went to high school in the Carlsbad Caverns!!!],
    q[My polyvinyl cowboy wallet was made in Hong Kong by Montgomery Clift!],
    q[My %s is built like a ... BAGEL with %s!!],
    q[My uncle Murray conquered Egypt in 53 B.C. And I can prove it too!!],
    q[.. My vaseline is %s...],
    q[NANCY!! Why is everything RED?!],
    q[%s... your %s were in a %s!! They're %s - They %shey had no %s... They had no %s... They did PILLS in %s... Nathan, %s them... but they were OFF-KEY...],
    q[%s has been %s!! %s has been %s!!],
    q[Nice decor!],
    q[Not enough people play SKEE-BALL.. They're always thinking about %s or and %s!!],
    q[NOT fucking!! Also not a %s of LOOSE-%s!!],
    q[Not %s... only ``%s''... and in need of %s... in PAIN!!!],
    q[NOW do I get to blow out the %s??],
    q[Now I am depressed...],
    q[Now I can join %s!],
    q[Now I need a suntan, a tennis lesson, Annette Funicello and two dozen Day-Glo orange paper jumpsuits!!],
    q[.. Now I think I just reached the state of %s that comes %s you see the TOTAL at the %s!],
    q[Now I understand the meaning of ``%s''!],
    q[Now I'm being %s shuffled closer to the %s with the %s in it!!],
    q[Now I'm concentrating on a specific tank battle toward the end of World War II!],
    q[Now I'm having %s about the beautiful, round wives of %s encased in %s and being approached by %s selling FRUIT..],
    q[Now I'm telling %s about %s!],
    q[.. Now KEN and %s are %s to MIND-%s..],
    q[Now KEN is having a %s beacuse his "R.V." %s are OVER-DUE!!],
    q[Now my %s are heavily committed to 23% of the %s and %s industry of the state of %s!!],
    q[Now that I have my ``APPLE,'' I comprehend %s!!],
    q[Now that we're in LOVE, you can BUY this %s for a 48% %s.],
    q[Now, I think it would be GOOD to buy FIVE or %s and %s for %s!!],
    q[NOW, I'm supposed to %s two, and HOLD th' MAYO!!],
    q[NOW, I'm taking the %s to %s so I can write POEMS about %s and sensuous PRE-TEENS!!],
    q[Now, let's %s for %s!!],
    q[Now, my %s is flashing before my EYES as I park my %s in your EXXON service area for a %s!!],
    q[O.K.! Speak with a %s!! Send out for %s!! Hop a JET!],
    q[Of course, you %s about the %s in the %s --],
    q[Oh my GOD -- the SUN just fell into %s!!],
    q[Oh, FISH sticks, %s, GIN fizz, %s!!],
    q[Oh, I get it!! ``The BEACH goes on,'' huh, SONNY??],
    q[OKAY!! Turn on the sound ONLY for %s, FULLY-%s.V.'S and %s!!],
    q[Okay, %s, I recognize you now!! Also %s, %s!! And %s!! Everybody into th' %s!],
    q[Okay.. I'm going home to write the ``%s's %s''..],
    q[%s?? Oh, YEH!! First you need 4 %s of JELL-O and a %s!!... I think you drop th'%s in the JELL-O as if it was a %s, or an %s... ...or...I...um... WHERE'S the %s?],
    q[On %s thought, maybe I'll heat up some %s and watch %s.. It's GREAT to be ALIVE!!],
    q[On the other hand, life can be an endless parade of %s aboard a cruise ship to %s if only we let it!!],
    q[On the road, ZIPPY is a pinhead without a purpose, but never without a POINT.],
    q[.. Once upon a time, four %s attacked a family of %s, %s and brought DOWN their %s!!],
    q[Once, there was NO fun... This was before MENU planning, %s statements or %s equipment... Then, in 1985.. FUN was completely encoded in this tiny %s.. It contain 14,768 vaguely amusing SIT-COM pilots!! We had to wait %s years but we finally got %s, MTV and a large selection of creme-filled snack cakes!],
    q[.. One %s coming up!!],
    q[ONE: I will donate my entire ``%s'' comic book collection to the downtown %s.. TWO: I won't START a BAND called ``%s & %s''.. THREE: I won't ever %s my %s again!!],
    q[.. or were you driving the %s that %s at me in MIAMI last Tuesday?],
    q[Our father who art in heaven.. I sincerely pray that %s at this table will PAY for my %s and %s.. and also leave a %s...],
    q[.. over in west Philadelphia a puppy is vomiting..],
    q[OVER the underpass! UNDER the overpass! Around the %s and %s!!],
    q[%s me, am I speaking %s?],
    q[Pardon me, but do you know what it means to be %s with your BOOTH!],
    q[%s is stealing %s to feed the babies in %s.],
    q[...%s are floating by...],
    q[PIZZA!!],
    q[Place me on a %s counter while you %s several %s in the Trianon Room!! Let me one of your %s!],
    q[Please come home with me... I have Tylenol!!],
    q[Psychoanalysis?? I thought this was a nude rap session!!!],
    q[%s!! %s!! %s!!],
    q[Put %s red %s in each %s!!],
    q[Quick, sing me the %s!!],
    q[QUIET!! I'm being %s!! Is it GREAT yet? It's s'posed to %s...],
    q[%s!!],
    q[RELAX!! ... This is gonna be a %s!! Besides, I work for %s!],
    q[Remember, if you try to %s, many %s will %s your %s!! This is your %s!!],
    q[Remember, in 2039, %s & PASTA will be availableONLY by prescription!!],
    q[%s in Glue!],
    q[%s comes down a %s wearing bright blue %s.. He scrubs the POPE with a mild soap or detergent for 15 minutes, starring %s!!],
    q[Send your questions to ``%s'', Box 40474, San Francisco, CA 94140, USA],
    q[SHHHH!! I hear %s-%s tossing %s into empty %s..],
    q[Should I do my %s medley?],
    q[.. Should I get locked in the %s'%s today -or have a %s??],
    q[Should I start with the time %s personalities with a %s hair stylist or my failure to refer five %s to a good %s?],
    q[Sign my %s.],
    q[So this is what it feels like to be potato salad],
    q[.. So, if we convert %s-%s into HIGH-%s-%s, the PRE-%s risks will %s to a rate of 2 %s per %s!!],
    q[.. someone in %s, Ohio is selling %s to a SERBO-%s],
    q[Someone is %s on my collar!!],
    q[Sometime in 1993 %s will lead a %s on GUAM!!],
    q[Somewhere in %s a prostitute is %s a %s!!],
    q[Somewhere in suburban Honolulu, an unemployed bellhop is whipping up a batch of illegal psilocybin chop suey!!],
    q[Somewhere in Tenafly, New Jersey, a chiropractor is viewing ``Leave it to Beaver''!],
    q[Sorry, wrong %s!!],
    q[Spreading peanut butter reminds me of opera!! I wonder why?],
    q[%s!! ...click...],
    q[Talking Pinhead Blues: Oh, %s my ``%s'' DOLL and I get BAD reception on channel %s-SIX!! Th'%s is closin' down and I just heard %s has been DEAD for YEARS.. (sniff) My %s collection was %s up by th'dog, %s won't let me take a %s 'til Easter.. (snurf) So I went to the kitchen, but %s whup me upside mah HAID!! (on no, no, no.. Heh, heh)],
    q[%s? You %s! Don't you realize that the END of the ``Wash Cycle'' is a %s for most people?!],
    q[%s are using %s in their %s!],
    q[Tex SEX! The HOME of %s! The dripping of %s!! Take me to Minnesota but don't %s me!!],
    q[Th' MIND is the Pizza Palace of th' SOUL],
    q[Th' %s... soaking... soaking... soaking... Th' %s... washing... washing... washing... Th' %s... rinsing... rinsing... rinsing...],
    q[Thank god!!.. It's %s!!],
    q[That's a decision that can only be made between you & %s!!],
    q[The appreciation of the average visual graphisticator alone is worth the whole suaveness and decadence which abounds!!],
    q[The entire %s'%s all share ONE personality -and have since BIRTH!!],
    q[The fact that 47 %s are yelling and sweat is cascading down my %s is fairly enjoyable!!],
    q[The %s lands on my HEAD and I become a %s...],
    q[.. the %s is made out of %s and my HONDAis a barbequed %s! Yum!],
    q[The Korean War must have been fun.],
    q["%s," I saw them at th' %s...],
    q[The %s of an %s is %s!!],
    q[.. the %s are in here with my %s!!],
    q[The Osmonds! You are all Osmonds!! Throwing up on a freeway at dawn!!!],
    q[The %s is %s for an END to %s movies!!],
    q[The %s were %s from 1952!! But they went to MARS around 1953!!],
    q[The %s keeps coming in and %s like a rayon MUU-MUU..],
    q[..The %s mounts as %s your %s according to ancient Tibetan %s..are you %s yet??],
    q[Then, it's off to %s!!],
    q[There's a little picture of %s doing %s to %s in a $200,000 %s!!],
    q[There's a lot of %s in %s if you have an AGENT!!],
    q[There's a SALE on %s down at the "7-11"!!],
    q[There's enough money here to buy 5000 cans of Noodle-Roni!],
    q[These %s should be FORCE-FED to %s!!],
    q[They collapsed.... like nuns in the street... they had no teen appeal!],
    q[They don't hire %s, Mr. Toad!],
    q[This %s really BOILS my BLOOD... He's so..so.....%s!!],
    q[This is a NO-%s flight -- hold th' %s!!],
    q[This is my %s memorial %s where I worship William Bendix like a GOD!!],
    q[This is %s!],
    q[This MUST be a good party -- My %s is being painfully pressed up against someone's %s!!],
    q[.. this must be what it's like to be a %s!!],
    q[This PIZZA symbolizes my %s!!],
    q[This %s knows his %s.. And he has ``VISA''!!],
    q[This %s my partygoing experience! Someone I DON'%s is talking to me about a HEART-%suropean film..],
    q[Those aren't WINOS--that's my %s, my %s, my %s, and my %s!!],
    q[Thousands of days of civilians ... have produced a... feeling for the aesthetic modules --],
    q[Three attractive %s are discussing %s and MAKE-%s with them!!],
    q[Today, %s from %s sold me a framed photo of %s before his %s!],
    q[Toes, knees, %s. Toes, knees, nipples, %s... Nipples, dimples, knuckles, %s, wrinkles, pimples!! I don't like %s or his %s.],
    q[%s! Is YOUR life a PATIO of FUN??],
    q[Two %s black dots and one BIG black dot...nice 'n' %s!!],
    q[Two with %s, hold th' BEETS..side of %s!],
    q[Uh-oh -- WHY am I suddenly thinking of a %s religious leader frolicking on a %s weekend?],
    q[Uh-oh!! I forgot to submit to %s!],
    q[UH-OH!! I put on ``%s-%s of the 50's'' by mistake!!!],
    q[UH-OH!! I think KEN is OVER-DUE on his R.V. %s and HE'S having a %s too!! Ha ha.],
    q[Uh-oh!! I'm having %s!!],
    q[UH-OH!! We're out of %s and %s!],
    q[...Um...Um...],
    q[Used staples are good with %s!],
    q[Vote for ME -- I'm well-tapered, half-cocked, ill-conceived and TAX-%s!],
    q[..Wait 'til those %s get back to their %s & discover them to be %s to the BRIM with %s!!],
    q[Wait.. is this a %s or the END of LIFE in Petticoat Junction??],
    q[Was my %s left out in th'RAIN? It tastes %s!!],
    q[We are now enjoying total mutual interaction in an imaginary hot tub...],
    q[We have %s amounts of HAIR --],
    q[We just joined the civil hair patrol!],
    q[We place two copies of %s magazine in a DARK, HUMID mobile home. 45 minutes later %s emerges wearing a %s on her head!],
    q[Well, here I am in %s.. %s it. %s it. %s it. %s it. %s it. %s it. %s it. %s it. %s.. %s are %s over me!!],
    q[Well, I'm a classic %s!! And I'm looking for a way to %s experience some reason to LIVE!!],
    q[Well, I'm %s.. I might as well pay a visit to the %s...],
    q[Well, I'm on the right planet---everyone looks like me!!!],
    q[Well, O.K. I'll compromise with my principles because of %s!],
    q[Were these parsnips %s in %s?],
    q[What a %s! I'm an authorized ``%s'' dealer!!],
    q[What GOOD is a %s suitcase %s?],
    q[What I need is a %s with a %s...],
    q[What I want to find out is -- do parrots know much about Astro-Turf?],
    q[What %s are they watching?],
    q[What %s is this, please??],
    q[What's the %sid?.. Is your %s unsatisfactory?],
    q[When I met th'POPE back in '58, I scrubbed him with a %s or %s for 15 minutes. He seemed to enjoy it..],
    q[When this load is %s think I'll wash it AGAIN..],
    q[When you get your PH.D. will you get able to work at %s?],
    q[When you said ``%s'' it reminded me of an overdue %s.. Don't you SEE? O'Grogan %s a %s and HAD to murder the %s who KNEW!!],
    q[Where do your SOCKS go when you lose them in th' %s?],
    q[Where does it go when you flush?],
    q[Where's my %s?],
    q[Where's %s?],
    q[Where's th' %s??],
    q[Where's the Coke machine? Tell me a joke!!],
    q[While I'm in %s thought I'd like to see the %s!!],
    q[While my %s is being refused service in %s, Jesuit priests are %s!!],
    q[While you're chewing, think of %s'S bank account.. This will have the same effect as two ``%s''!],
    q[WHO sees a %s sobbing on a %s?!],
    q[Who wants some %s with SEN-SEN an' %s?],
    q[WHOA!! I'm having a %s right NOW!!],
    q[WHOA!! Ken and Barbie are having %s!! It must be the %s!!],
    q[Why am I in this ROOM in %s?],
    q[Why are these athletic shoe salesmen following me??],
    q[WHY are we missing KOJAK?],
    q[Why don't you ever enter and %s, Marvin?? Don't you know your own %s?],
    q[Why is everything made of Lycra Spandex?],
    q[Why is it that when you DIE, you can't take your %s with you??],
    q[Why was %s?],
    q[Will it improve my %s?],
    q[Will the third world war keep ``Bosom Buddies'' off the air?],
    q[Will this never-ending series of %s never cease?],
    q[With this weapon I can expose fictional characters and bring about sweeping reforms!!],
    q[With YOU, I can be %s.. We don't %san Rather..],
    q[World War Three can be averted by adherence to a strictly enforced dress code!],
    q[Wow! Look!! A stray meatball!! Let's interview it!],
    q[Xerox your lunch and file it under ``sex offenders!''],
    q[Yes, but will I see the %s in skintight leather at an %s concert?],
    q[Yes, Private %s!!],
    q[You can't hurt me!! I have an %s!!],
    q[You mean now I can %s in the back and further BLUR th' distinction between %s and %s?],
    q[You mean you don't want to watch %s from %s?],
    q[You must be a %s!! Have you made your MONEY-DROP today??],
    q[%s'%s!!],
    q[You should all %s for %s while I decide on a %s!!],
    q[You were s'posed to laugh!],
    q[YOU!! Give me the %s, %s, most charming little %s you can find!! An make it %s!!],
    q[YOU'D cry too if it happened to YOU!!],
    q[Your %s sit like twin %s above a MOUTH that knows no %s --],
    q[Youth of today! Join me in a mass rally for traditional mental attitudes!],
    q[Yow!],
    q[Yow! Am I cleansed yet?!],
    q[Yow! Am I having fun yet?],
    q[Yow! Am I in Milwaukee?],
    q[Yow! Am %s yet??],
    q[Yow! And then we could sit on the hoods of cars at stop lights!],
    q[Yow! Are we in the perfect mood?],
    q[Yow! Are we laid back yet?],
    q[Yow! Are we wet yet?],
    q[Yow! Are you the self-frying president?],
    q[Yow! Did something bad happen or am I in a drive-in movie??],
    q[YOW! I can see 1987!! %s is doing the %s of "%s"...he's playing %s!!],
    q[Yow! I forgot my PAIL!!],
    q[Yow! I just went below the poverty line!],
    q[Yow! I like my new %s...],
    q[Yow! I threw up on my window!],
    q[Yow! I want my nose in lights!],
    q[Yow! I want to mail a bronzed artichoke to Nicaragua!],
    q[Yow! I'm having a quadraphonic sensation of two winos alone in a steel mill!],
    q[Yow! I'm imagining a surfer van filled with soy sauce!],
    q[Yow! I'm out of work...I could go into shock absorbers...or %s!!],
    q[Yow! I'm %s!],
    q[Yow! Is my fallout shelter termite proof?],
    q[Yow! Is this sexual intercourse yet?? Is it, huh, is it??],
    q[Yow! It's a hole all the way to downtown Burbank!],
    q[Yow! It's some people inside the wall! This is better than mopping!],
    q[Yow! Maybe I should have asked for my Neutron Bomb in %s--],
    q[Yow! Now I get to think about all the %s did to a %s when I was in %s!],
    q[Yow! Now we can become alcoholics!],
    q[Yow! %s..],
    q[Yow! Those people look exactly like Donnie and Marie Osmond!!],
    q[Yow! We're going to a new disco!],
    q[YOW!!],
    q[Yow!! "Janitor trapped in sewer uses ESP to find decayed burger"!!],
    q[YOW!! Everybody out of the %s!],
    q[YOW!! I am having FUN!!],
    q[YOW!! I'm in a very clever and adorable %s!!],
    q[Yow!! It's %s and %s!! High on a HILL... driving a %s... I wanna be in that %s, too!! I wanna drive off with LIBBY and %s!],
    q[YOW!! Now I understand advanced %s and th' new %s laws!!],
    q[YOW!! Now I'm playing with my %s pinball machine!! %s is in the %s!!],
    q[Yow!! That's a %s!! Eating a whole FIELD of %s should make you feel %s!!],
    q[YOW!! The land of the rising SONY!!],
    q[YOW!! Up ahead! It's a %s!!],
    q[YOW!! What should the entire human race DO?? Consume a fifth of %s, ski NUDE down MT. %s, and have a wild %s!],
    q[YOW!!! I am having fun!!!],
    q[YUGGA-HUGGA-BUGGA-TUGGA!! HEY-HEY!! %s!! No, a %s!! An %s!! No, I think it's a %s!!!],
    q[Zippy's brain cells are straining to bridge synapses...],
);

my @caps = (
    q[A GRAM],
    q[ACCEPT YOU],
    q[AIEEEEE],
    q[ALCOHOLIC],
    q[ALFRED JARRY],
    q[ALL RIGHT],
    q[ALUMINUM SILICATE],
    q[AMAZED],
    q[AMERICA],
    q[AMPHIBIOUS HOG CALLERS],
    q[ANAL RETENTIVE],
    q[ANN JILLIAN],
    q[ANN LANDERS],
    q[ANSWERS],
    q[ANYTHING],
    q[ANYWHERE],
    q[APPLE],
    q[ARTIST],
    q[ASEXUAL PIG],
    q[ASHTRAY],
    q[ASK ZIPPY],
    q[ASPARAGUS],
    q[ASSUMABLE MORTGAGE],
    q[ATLANTIC CITY],
    q[ATLANTIC CITY],
    q[AUTOMOBILE PARTS],
    q[BABY HUEY],
    q[BALD HERO],
    q[BANK ROBBERS],
    q[BARBARA STANWYCK],
    q[BARBRA STREISAND],
    q[BARRY],
    q[BEACH],
    q[BEAUTIFUL THOUGHTS],
    q[BEEF JERKY],
    q[BEEP],
    q[BELA LUGOSI],
    q[BIG BANG THEORY],
    q[BIG MONEY],
    q[BIG MUSCLES],
    q[BIKINI BEACH],
    q[BIOLOGICAL ALARM CLOCK],
    q[BLACK HOLE],
    q[BOBBIE VINTON],
    q[BODY],
    q[BOISE],
    q[BOOZE],
    q[BORSCHT],
    q[BOSSA NOVA],
    q[BOTH],
    q[BOTH T],
    q[BOWLING BALL],
    q[BOWLING WORLD],
    q[BRADY BUNCH],
    q[BRAINPAN],
    q[BRATWURST],
    q[BRILL CREAM],
    q[BUDAPEST NATIONAL ANTHEM],
    q[BUFFER],
    q[BURGER KING],
    q[BURN],
    q[BUY],
    q[CALIFORNIA],
    q[CANS],
    q[CAR WASH],
    q[CAREER],
    q[CARTOON GUYS],
    q[CASH FLOW],
    q[CASIO],
    q[CATHOLIC SCHOOLGIRL],
    q[CELLS],
    q[CHANNEL],
    q[CHARTS],
    q[CHEEKS],
    q[CHINESE WOMEN],
    q[CHIVAS REGAL],
    q[CHUBBY CHECKER],
    q[CHURCH],
    q[CODE],
    q[COINCIDENCE],
    q[COLLEGE GRADUATE],
    q[COLOR T],
    q[COMBING],
    q[COMPULSORY URINALYSIS],
    q[CONCEPTION],
    q[CONCEPTS],
    q[CONCERN],
    q[CONCERNED],
    q[CONFESS],
    q[CONGRATULATIONS],
    q[CONTESTS],
    q[CONTROLLED],
    q[CORDOVANS],
    q[CORN],
    q[CORRECTLY MARINATED],
    q[COUSIN],
    q[CRANE OPERATOR],
    q[CRIPPLED ACCOUNTANT],
    q[CUB SCOUT],
    q[CUTEST],
    q[DAFFY DUCK EXHIBIT],
    q[DARK SHADOWS],
    q[DATING GAME],
    q[DAYTON],
    q[DECADENT SUBWAY SCENE],
    q[DEEP],
    q[DENTAL PLAN],
    q[DENTIST],
    q[DESK],
    q[DESPONDENT],
    q[DESPONDENT],
    q[DIDI],
    q[DIE],
    q[DIFFERENCE],
    q[DIFFERENT],
    q[DIGITAL READ],
    q[DIGITAL WATCH],
    q[DISGUISE],
    q[DOBERMAN],
    q[DOING],
    q[DONNY AND MARIE],
    q[DONUT HUT],
    q[DOWNTOWN BURBANK],
    q[DREAM],
    q[DRESSING ROOM],
    q[DROOLING],
    q[DUSTIN HOFFMAN],
    q[EARS],
    q[EARS],
    q[EASTER BUNNY],
    q[ED MCMAHON],
    q[EGG EXTENDERS],
    q[EGG SALAD],
    q[EGGS],
    q[EIGHTIES],
    q[ELBOW],
    q[ELEVATOR],
    q[EMOTE],
    q[EMOTIONAL],
    q[EMOTIONAL OUTBURST],
    q[EMOTIONAL RESOURCES],
    q[ENTIRE LIFE],
    q[ESCAPE],
    q[ESCROW],
    q[ESP],
    q[EUBIE BLAKE],
    q[EXCITED],
    q[EXCRUCIATING PAIN],
    q[EXISTENTIAL DESPAIR],
    q[FAD],
    q[FALAFEL SANDWICH],
    q[FAMOUS],
    q[FAVORITE],
    q[FEELINGS],
    q[FEW],
    q[FIRST],
    q[FISH],
    q[FISH],
    q[FISHWICH],
    q[FIVE DOZEN],
    q[FLAG DAY],
    q[FLANK STEAK],
    q[FLATBUSH],
    q[FLIPPING AROUND],
    q[FLORIDA],
    q[FLUFFO],
    q[FOLD],
    q[FOOLED],
    q[FORMALDEHYDE],
    q[FORTY],
    q[FRENCH FRIES],
    q[FRILLS],
    q[FROZEN ENTREES],
    q[FRUIT PICKERS],
    q[FUN],
    q[FUN],
    q[FUN THING],
    q[FUNDAMENTALIST],
    q[FUR],
    q[GAIN WEIGHT],
    q[GENETIC POOL],
    q[GENIUS],
    q[GIN],
    q[GLISTENS],
    q[GOD],
    q[GOLDIE HAWN],
    q[GOOD],
    q[GOOD],
    q[GOOD IDEA],
    q[GORRY],
    q[GRADUATE SCHOOL],
    q[GREAT],
    q[GREAT HEAD],
    q[GUM],
    q[GUYS],
    q[HAIR CUTS],
    q[HAIR TONICS],
    q[HALT PRODUCTION],
    q[HALVAH],
    q[HAPPY],
    q[HEALTHY],
    q[HEAVILY FORESTED],
    q[HEDGES],
    q[HELLO],
    q[HELLO KITTY],
    q[HENNY YOUNGMAN],
    q[HERE],
    q[HIGHWAY],
    q[HITCHHIKING],
    q[HOLOGRAPHIC ATOMIC SIMULATION LASER],
    q[HOME],
    q[HOORAY],
    q[HOT],
    q[HOT TUB],
    q[HOUSE OF REPRESENTATIVES],
    q[HOW],
    q[HOWARD COSELL],
    q[HUBUB],
    q[HUGH BEAUMONT],
    q[HUMAN REPLICAS],
    q[HUMOR],
    q[HYPERTENSION],
    q[I BORN],
    q[I EVER],
    q[I FORGOT],
    q[I HATE RUBIK],
    q[I HAVE],
    q[I HIJACKED],
    q[I JOGGING],
    q[I KAISER ROLL],
    q[I LIKE],
    q[I LIKE A],
    q[I LOST],
    q[I OWN],
    q[I SELL OUT],
    q[I SHOPLIFTING],
    q[I SWITCHED],
    q[IDEA],
    q[IMAGINING],
    q[IMPUDENT NOSE],
    q[IMPULSE ITEM],
    q[IMPUNITY],
    q[INCORRECT THING],
    q[INK],
    q[INSANE ASYLUM],
    q[INSIDE],
    q[INSIPID THOUGHTS],
    q[INTESTINAL TRACT],
    q[INVISIBLE AGAIN],
    q[INVOLUNTARILY],
    q[IRON CURTAIN],
    q[IS],
    q[ITALIAN TEENAGERS],
    q[IVY],
    q[JAPAN],
    q[JERRY FALWELLING],
    q[JOHN TRAVOLTA],
    q[JOKE],
    q[JUGULAR],
    q[JUMP UP AND DOWN],
    q[JUNK FOOD],
    q[KARL MALDEN],
    q[KATRINKA],
    q[KEN],
    q[KILL],
    q[KING BOMBA],
    q[KIRKEGAARD],
    q[KOREAN STEAK KNIVES],
    q[LAS VEGAS],
    q[LBJ],
    q[LEGALIZED],
    q[LESLIE GORE],
    q[LEVELS],
    q[LEVITTOWN],
    q[LIBERACE],
    q[LIBRARY CARD],
    q[LIFE],
    q[LIGHT],
    q[LINDA RONSTADT],
    q[LISTENS],
    q[LITTLE],
    q[LOGARITHM],
    q[LOOK],
    q[LOU GRANT],
    q[LOVE],
    q[LOVE],
    q[M SHAVING],
    q[MAGNATES],
    q[MAIL],
    q[MAJOR CONTRACT DISPUTE],
    q[MAMBO],
    q[MATTER S],
    q[MATURE RELATIONSHIP],
    q[MAUREEN],
    q[MAYO],
    q[ME],
    q[MEER],
    q[MELBA],
    q[MEMORIZE],
    q[MENTAL HYGIENE],
    q[MENTALLY],
    q[MERYL STREEP],
    q[METHADONE PROGRAM],
    q[METRO],
    q[MICROBIOLOGY],
    q[MID],
    q[MIND],
    q[MISS PIGGY],
    q[MMMMMM],
    q[MODULAR LOVE UNITS],
    q[MORE FUN],
    q[MOUSSE],
    q[MOUTH],
    q[MUST],
    q[MY],
    q[MYSTERIANS],
    q[NANCY],
    q[NANCY SINATRA],
    q[NATHAN],
    q[NEGATIVITY],
    q[NEGOTIATIONS],
    q[NEW SHIRT],
    q[NEWARK],
    q[NEXT FLIGHT],
    q[NIPPLES],
    q[NO],
    q[NO HOPE],
    q[NO USE],
    q[NORTH],
    q[NOSE],
    q[NOSE JOB],
    q[NOT],
    q[NOUVELLE CUISINE],
    q[NOW],
    q[NUCLEAR WASTE DUMP],
    q[NYLON OIL WELLS],
    q[OBVIOUS],
    q[OEDIPUS COMPLEX],
    q[OKAY],
    q[OKAY],
    q[OMNIVERSAL AWARENESS],
    q[ONLY],
    q[OVER],
    q[OVERDRAWN],
    q[OVULAR],
    q[OYSTERS],
    q[PACKAGE],
    q[PAIL],
    q[PAISLEY],
    q[PAMPERS],
    q[PARDON],
    q[PARENT],
    q[PASTRY],
    q[PED],
    q[PEGGY FLEMING],
    q[PENGUINS],
    q[PENIS ENVY],
    q[PEOPLE],
    q[PEORIA],
    q[PERSONAL PINHEADS],
    q[PETITION],
    q[PHIL SILVERS],
    q[PHILADELPHIA ACCENT],
    q[PILLSBURY DOUGHBOY],
    q[PINHEAD],
    q[PINK SOCK],
    q[PINK SOCKS],
    q[PIZZA],
    q[PIZZA],
    q[PLANS],
    q[PLEASANT],
    q[PLEASURABLE EVENTS],
    q[PLUMBER],
    q[POLICE],
    q[POLYESTER],
    q[POLYVINYL CHLORIDE],
    q[PONTIAC],
    q[POPE],
    q[POPULARITY CONTEST],
    q[PORCUPINE],
    q[POSTERIOR OLFACTORY LOBULE],
    q[POSTMASTER GENERAL],
    q[POT FARM],
    q[POURED],
    q[POWER],
    q[PRESERVES],
    q[PRESIDENT FORD],
    q[PREVIOUS LIFE],
    q[PRINCE],
    q[PRINCIPAL],
    q[PROGRAM],
    q[PRUNE CRISPS],
    q[PUNK ROCK],
    q[QUIET],
    q[QUIETLY],
    q[RADAR],
    q[RAMBLER METROPOLITAN],
    q[RANCID CORN DOG],
    q[RAPING],
    q[RAW],
    q[RAY VISION],
    q[REAL PEOPLE],
    q[REAL ROUND],
    q[RED CHINA],
    q[RELATIVES],
    q[RELAX],
    q[RELIGIOUS],
    q[RELIGIOUS EXPERIENCE],
    q[REVOLUTIONARY HAIR PRODUCTS],
    q[RHAPSODY],
    q[RINSE CYCLE],
    q[ROAST BEEF],
    q[ROCK],
    q[ROLL],
    q[RONDO],
    q[ROOM],
    q[ROOM],
    q[RUNNING],
    q[SALE],
    q[SAME WAVE],
    q[SANDY DUNCAN],
    q[SANFORIZE],
    q[SANTA CLAUS],
    q[SARDINE ON WHEAT],
    q[SCRAMBLE],
    q[SCRAMBLED EGGS],
    q[SCUBA GEAR],
    q[SECOND],
    q[SEND OUT],
    q[SENSUOUS],
    q[SEVEN MILLION],
    q[SEVENTH HUSBAND],
    q[SEVENTIES],
    q[SEX],
    q[SEXUALLY ACTIVE],
    q[SHARKSKIN SLACKS],
    q[SHAVE],
    q[SHHHH],
    q[SHOOT YOU],
    q[SHOPPING MALL],
    q[SKEE],
    q[SLEEPING],
    q[SNACK CAKES],
    q[SNOOPY POSTER],
    q[SOAP OPERA],
    q[SOBBING],
    q[SOCIAL WORKER],
    q[SOCKS],
    q[SOFTWARE],
    q[SOMEBODY],
    q[SONY],
    q[SOPHISTICATED],
    q[SOY LOAF],
    q[SOY SAUCE],
    q[SPECIAL],
    q[SPECIAL EFFECTS],
    q[SPEED QUEEN],
    q[SPINNING],
    q[STAY],
    q[STEVEN SPIELBERG],
    q[STEWED PRUNES],
    q[STOP],
    q[STRIKE],
    q[STYROFOAM],
    q[SUPPER],
    q[SUPPLY],
    q[SWEDISH MOVIE],
    q[SWISS ALPS],
    q[SWITCH],
    q[SY SPERLING],
    q[TAILFINS],
    q[TAKE IT HOME],
    q[TALLULAH BANKHEAD],
    q[TAPPING],
    q[TATTOOED MIDGETS],
    q[TENDER VITTLES],
    q[TENSION],
    q[TERMINAL],
    q[THE LITTLE PINK FLESH SISTERS],
    q[THE MOD SQUAD],
    q[THERE],
    q[THING],
    q[THIS],
    q[THREE WINOS],
    q[THROW OVER],
    q[TIDY BOWL],
    q[TINY BOWL],
    q[TOAD],
    q[TOILET SEATS],
    q[TONY RANDALL],
    q[TOO MUCH FUN],
    q[TOP],
    q[TOPS OFF],
    q[TOYOTA],
    q[TRAINED SEALS],
    q[TRANSSEXUAL QUILTING BEES],
    q[TRIBUTE],
    q[TROUT],
    q[TROY DONAHUE],
    q[TRULY ALIVE],
    q[TRULY ONE],
    q[TYPE],
    q[UNDERSTAND],
    q[UNEMPLOYED],
    q[UNICORN],
    q[UNIVERSE],
    q[VEGETARIAN BURRITO],
    q[VETERINARIAN],
    q[VIEWING],
    q[VIOLENT],
    q[VISION],
    q[WALL],
    q[WALLET],
    q[WASTE DUMPS],
    q[WAYNE NEWTON],
    q[WEIGHT WATCHERS],
    q[WESSON OIL],
    q[WHIRLING BUFFERS],
    q[WHITE HOUSE],
    q[WHOA],
    q[WILLIAM BENDIX],
    q[WINOS],
    q[WOO],
    q[WORLD],
    q[WOUNDED SEAL],
    q[WRESTLING],
    q[WRITE],
    q[WRITING],
    q[WRONG TURN],
    q[YOU],
    q[YOU],
    q[YOU PICKED KARL MALDEN],
    q[YUGGA],
    q[YUGOSLAVIAN],
    q[ZIP CODE],
    q[ZIPPY],
);

my $q = CGI->new();

my $txt = $q->param('txt');
my $line = defined $txt ? $txt : $lines[rand @lines];
my $s =()= $line =~ m/%s/g;

for (1..$s) {
    $line =~ s/%s/$caps[rand @caps]/e;
}

print $q->header();
print $line;
